services:
  - type: web
    name: botcalls
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: PORT
        value: 10000